#!/bin/bash
#export LD_LIBRARY_PATH-/usr/lib/oracle/12.1/client64/lib

sqlplus64 "***/***@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

/* populates the tables */
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('James Bond', '007', 'casinoroyale@gmail.com', '25', '1234567890', '12', 'Comedy', 'Muscial', 'Animated', 'Robots');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Santa Claus', 'hohoho', 'northpole@gmail.com', '100', '0101010101', '45', 'Action', 'CGI', 'Super Heroes', 'Crime');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Queen Elizabeth', 'royal', 'hermajesty@msn.com', '92', '5656565656', '58', 'Animated', 'Children', 'Comedy', 'Musical');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Bruce Wayne', 'gotham1234', 'imbatman@msn.com', '32', '7878787878', '31', 'Drama', 'Crime', 'Historical', 'Classic');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Mark Zuckerberg', 'facebook', 'facebook@msn.com', '56', '7875614878', '11', 'Drama', 'Crime', 'Historical', 'Classic');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Jeff Bezos', 'amazon', 'amazonguy@msn.com', '45', '7875891878', '13', 'Muscial', 'Crime', 'Historical', 'Classic');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Bill Gates', 'msdos', 'msdos@msn.com', '52', '7877531878', '14', 'Drama', 'Crime', 'Historical', 'Muscial');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Melinda Gates', 'happy', 'micro@msn.com', '23', '7881547878', '15', 'CGI', 'Action', 'Children', 'Classic');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Larry Page', 'google', 'google@msn.com', '24', '7876523878', '16', 'Comedy', 'Crime', 'Historical', 'Classic');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Harvey Dent', 'gotham0101', 'lawyer@msn.com', '52', '7878741278', '17', 'Muscial', 'Action', 'Children', 'Classic');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Peter Parker', 'spiderman', 'spiderman@msn.com', '61', '7802017878', '59', 'Comedy', 'Muscial', 'Animated', 'Robots');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Tyrion Lannister', 'paydebts', 'hearmeroar@msn.com', '42', '6251487878', '32', 'Comedy', 'CGI', 'Super Heroes', 'Crime');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Tyrion Lannister2', 'imadwarf', 'hearmeroar@msn.com', '42', '8754887878', '22', 'Animated', 'Children', 'Comedy', 'Musical');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Bruce Wayne1234', 'batman', 'imbatman@msn.com', '32', '6523787878', '46', 'Comedy', 'Action', 'Historical', 'Classic');
INSERT INTO client (USERNAME, PASSWORD, EMAIL, AGE, CREDITCARD#, PROMO#, GENREPREF, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Queen Elizabeth1776', 'lizzy', 'hermajesty@msn.com', '52', '8925787878', '60', 'CGI', 'Crime', 'Historical', 'Classic');

INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('The Godfather', TO_DATE('2021-10-04 21:16:58', 'YYYY-MM-DD HH24:MI:SS'), '50', '1000', 'Crime', 'Drama', 'Classic');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Frozen', TO_DATE('2004-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '45', '1520', 'Animated', 'Musical', 'Children');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Lion King', TO_DATE('2001-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '64', '1600', 'Animated', 'Children', 'Animals');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('The Avengers', TO_DATE('2002-02-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '75', '1204', 'Super Hero', 'Action', 'CGI');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Frozen 2', TO_DATE('2014-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '15', '1410', 'Animated', 'Musical', 'Children');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Forrest Gump', TO_DATE('1985-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '7', '4440', 'Drama', 'America', 'History');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('The Green Mile', TO_DATE('2015-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '72', '5500', 'Crime', 'Drama', 'Science Fiction');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Imitation Game', TO_DATE('2004-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '52', '6400', 'History', 'Drama', 'World War 2');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('A Beautiful Mind', TO_DATE('1990-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '42', '4570', 'Drama', 'Math', 'Thriller');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Grease', TO_DATE('2014-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '6', '1428', 'Classic', 'Musical', 'Dancing');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Top Gun', TO_DATE('2005-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '16', '1450', 'Action', 'Adventure', 'Drama');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Die Hard', TO_DATE('1985-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '75', '7820', 'Action', 'Christmas', 'Classic');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Moulin Rouge', TO_DATE('2007-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '44', '1020', 'History', 'Musical', 'Drama');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Up', TO_DATE('1996-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '88', '1420', 'Animated', 'Flying', 'Children');
INSERT INTO video (TITLE, RELEASE_DATE, TIMES_WATCHED, DURATION_WATCHED, TAGWORD1, TAGWORD2, TAGWORD3) 
    VALUES ('Field of Dreams', TO_DATE('2014-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '12', '1820', 'Drama', 'Classic', 'Sports');

INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Laughter', '12', 'Frozen', 'Monty Python', 'Rick and Morty', 'Parks and Rec', 'Untitled Comedy', 'Arrested Development');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Explosions', '45', 'The Avengers', 'Transformers', 'Batman', 'Spiderman', 'Die Hard', 'Fast and the Furious');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Family Fun', '58', 'Lion King', 'Frozen', 'Up', 'Finding Nemo', 'Mulan', 'Shreck');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Serious', '31', 'The Godfather', 'The Pianist', 'The Imitation Game', 'Game of Thrones', 'True Detective', 'The Watchmen');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Relax', '11', 'Frozen', 'Monty Python', 'Rick and Morty', 'Parks and Rec', 'Untitled Comedy', 'Arrested Development');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Christmas', '13', 'A Christmas Carol', 'Its a Wonderful Life', 'Batman', 'Spiderman', 'Die Hard', 'Fast and the Furious');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Animated', '14', 'Lion King', 'Frozen', 'Up', 'Finding Nemo', 'Mulan', 'Shreck');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('CGI', '15', 'Transformers', 'The Avengers', 'Jurassic Park', 'Game of Thrones', 'True Detective', 'The Watchmen');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Emotions', '16', 'A Beautiful Mind', 'Forrest Gump', 'Rick and Morty', 'Parks and Rec', 'Untitled Comedy', 'Arrested Development');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Talking', '17', 'The English Patient', 'Transformers', 'Batman', 'Spiderman', 'Die Hard', 'Fast and the Furious');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Thinking', '59', 'The Imitation Game', 'Frozen', 'Up', 'Finding Nemo', 'Mulan', 'Shreck');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('History', '32', 'Dunkirk', 'The Pianist', 'The Imitation Game', 'Game of Thrones', 'True Detective', 'The Watchmen');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Laughter2', '22', 'Monty Python', 'Blazing Saddles', 'Rick and Morty', 'Parks and Rec', 'Untitled Comedy', 'Arrested Development');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Explosions2', '46', 'The Matrix', 'Transformers', 'Batman', 'Spiderman', 'Die Hard', 'Fast and the Furious');
INSERT INTO promo (PROMONAME, PROMO#, TOPVID1, TOPVID2, TOPVID3, NEWVID1, NEWVID2, NEWVID3) 
    VALUES ('Family Fun2', '60', 'Mulan', 'Frozen', 'Up', 'Finding Nemo', 'Mulan', 'Shreck');

INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('123', 'Bruce Wayne', TO_DATE('2002-02-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('124', 'Queen Elizabeth', TO_DATE('2005-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('125', 'Santa Claus', TO_DATE('2003-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('126', 'James Bond', TO_DATE('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('127', 'Harvey Dent', TO_DATE('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('128', 'Bruce Wayne', TO_DATE('2002-02-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('129', 'Queen Elizabeth1776', TO_DATE('2005-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('130', 'Santa Claus', TO_DATE('2003-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('131', 'Tyrion Lannister', TO_DATE('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('132', 'James Bond', TO_DATE('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('133', 'Bruce Wayne', TO_DATE('2002-02-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('134', 'Queen Elizabeth', TO_DATE('2005-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('135', 'Santa Claus', TO_DATE('2003-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('136', 'Peter Parker', TO_DATE('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO payment (PAYMENT#, USERNAME, SUBEXDATE) VALUES ('137', 'James Bond', TO_DATE('2024-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Disney', '12345', 'Frozen', '1000000', '6471234567', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('HBO', '12346', 'Game of Thrones', '1200000', '6472222222', TO_DATE('2003-04-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Marvel', '12356', 'The Avengers', '2000000', '4161234567', TO_DATE('2001-02-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Paramount', '56789', 'The Godfather', '900000', '4164567891', TO_DATE('2005-04-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Fox', '12347', 'Broken Arrow', '1600000', '6471454567', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('MGM', '12348', 'Goldeneye', '1240000', '6471344567', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Universal', '12359', 'Jurassic Park', '2100000', '6471454567', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Amazon', '56790', 'The Boyz', '940000', '6471987567', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Netflix', '12349', 'Squid Game', '1800000', '6471237657', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('WB', '12313', 'Batman', '1210000', '6471265567', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Lucasfilm', '12314', 'Star Wars', '2040000', '6471294567', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Ghibli', '56791', 'Grave of the Fireflies', '910000', '6471274267', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Dreamworks', '12378', 'Shreck', '1100000', '6471759567', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Pixar', '12379', 'Toy Story', '2200000', '6471262567', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO producer (PRODUCERNAME, LICENCE#, AVAILABLEVIDEOS, LICENSINGCOST, PRODUCERPHONE, EXPDATE) 
    VALUES ('Happy', '12380', 'The Happy Story', '2100000', '6476544567', TO_DATE('2002-05-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));


exit;
EOF
